// Type-safe runtime data loader. Each dataset is fetched once and cached
// in-memory for the lifetime of the page. Data lives in /public/data/*.json
// and is regenerated by scripts/update_data.py independently of the build.
//
// Two-tier cache:
//   - `peek(url)` returns the cached value synchronously, or undefined.
//     Consumers use it as the initial state of useAsyncData, which avoids the
//     loading-flash on every component remount after the first fetch.
//   - `load(url)` returns a memoised Promise that populates the sync cache
//     when it resolves.

import type { RatingCompany } from './ratingData';
import type { Article } from './articlesData';
import type { CompanyDetails } from './companyDetails';
import type { Bond, SiteLoan, Corporate, AllInvestment } from './investmentData';
import type { LogoMap } from './logoMap';

const syncCache = new Map<string, unknown>();
const pending   = new Map<string, Promise<unknown>>();

async function fetchJson<T>(url: string): Promise<T> {
  const res = await fetch(url);
  if (!res.ok) throw new Error(`Failed to load ${url}: ${res.status}`);
  return res.json() as Promise<T>;
}

export function load<T>(url: string): Promise<T> {
  const cached = pending.get(url);
  if (cached) return cached as Promise<T>;
  const promise = fetchJson<T>(url).then(value => {
    syncCache.set(url, value);
    return value;
  });
  pending.set(url, promise);
  return promise;
}

export function peek<T>(url: string): T | undefined {
  return syncCache.get(url) as T | undefined;
}

// ── Public dataset loaders ─────────────────────────────────────────

export const URLS = {
  rating:                 '/data/rating.json',
  logoMap:                '/data/logo-map.json',
  articles:               '/data/articles.json',
  companyDetails:         '/data/company-details.json',
  investmentBonds:        '/data/investment-bonds.json',
  investmentLoans:        '/data/investment-loans.json',
  investmentCorporates:   '/data/investment-corporates.json',
  investmentAll:          '/data/investment-all.json',
} as const;

export const loadRatingData         = () => load<RatingCompany[]>(URLS.rating);
export const loadLogoMap            = () => load<LogoMap>(URLS.logoMap);
export const loadArticles           = () => load<Article[]>(URLS.articles);
export const loadCompanyDetails     = () => load<Record<string, CompanyDetails>>(URLS.companyDetails);
export const loadInvestmentBonds      = () => load<Bond[]>(URLS.investmentBonds);
export const loadInvestmentLoans      = () => load<SiteLoan[]>(URLS.investmentLoans);
export const loadInvestmentCorporates = () => load<Corporate[]>(URLS.investmentCorporates);
export const loadInvestmentAll        = () => load<AllInvestment[]>(URLS.investmentAll);
